import { expect, test } from '@playwright/test'

import { adminPassword, login, revealPasswordField, selectAppOption, uniqueSuffix, waitForUiReady } from './helpers'

test('系统设置与执行计划表单动作正常', async ({ page }) => {
  test.setTimeout(60000)
  await login(page)

  await page.goto('/settings')
  await waitForUiReady(page)
  await page.locator('#settings-admin-password').fill(adminPassword)
  await page.locator('#settings-admin-password-confirm').fill('different-password')
  await page.getByRole('button', { name: /更新密码|Update Password/ }).click()
  await expect(page.getByText(/两次输入的密码不一致|passwords do not match/)).toBeVisible()

  await page.locator('#settings-admin-password-confirm').fill(adminPassword)
  await revealPasswordField(page, '#settings-admin-password')
  await page.locator('#settings-admin-password').fill(adminPassword)
  await page.getByRole('button', { name: /更新密码|Update Password/ }).click()
  await expect(page.getByText(/管理员密码已更新|Admin password updated/)).toBeVisible()

  await selectAppOption(page, '#settings-debug', /已启用|Enabled/)
  await selectAppOption(page, '#settings-debug', /已禁用|Disabled/)
  await selectAppOption(page, '#settings-main-engine', /旧脚本主链|Legacy Script Chain/)
  await selectAppOption(page, '#settings-main-engine', /任务中心引擎|Task Center Engine/)
  await selectAppOption(page, '#settings-browser-strategy', /传统浏览器|Legacy/)
  await selectAppOption(page, '#settings-browser-strategy', /仅 HTTP|HTTP-only/)
  await selectAppOption(page, '#settings-browser-enabled', /已启用|Enabled/)
  await selectAppOption(page, '#settings-browser-enabled', /已禁用|Disabled/)
  await page.locator('#notification-email_to').fill('ops@example.com')
  await page.locator('#notification-email_pass').fill('mail-secret')
  await revealPasswordField(page, '#notification-email_pass')
  await page.locator('#notification-email_pass').fill('mail-secret')
  await page.getByRole('button', { name: /保存设置|Save Settings/ }).click()
  await expect(page.getByText(/设置已保存|Settings saved/)).toBeVisible()

  await page.goto('/schedules')
  await waitForUiReady(page)
  await selectAppOption(page, '#schedule-main_checkin-enabled', /已禁用|Disabled/)
  await page.locator('#schedule-main_checkin-cron').fill('*/15 * * * *')
  await page.locator('#schedule-main_checkin-timezone').fill('Asia/Shanghai')
  await page.locator('#schedule-main_checkin-cooldown').fill('15')
  await page.getByRole('button', { name: /保存调度|Save Schedule/ }).first().click()
  await expect(page.getByText(/调度已保存|Schedule saved/)).toBeVisible()
})

test('主链路配置、补充任务、确认按钮和运行日志动作正常', async ({ page }) => {
  test.setTimeout(60000)
  await login(page)
  const suffix = uniqueSuffix('config')

  await page.goto('/main-checkin')
  await waitForUiReady(page)
  await page.locator('details').filter({ hasText: /自定义提供商|Custom Providers/ }).locator('summary').click()
  await page.locator('#main-checkin-providers').fill('{bad-json')
  await page.getByRole('button', { name: /保存配置|Save Config/ }).first().click()
  await expect(page.getByText(/JSON 格式不正确|Invalid JSON/)).toBeVisible()

  await page.locator('#main-checkin-providers').fill('{}')
  await page.locator('#main-checkin-account-0-name').fill(`Main ${suffix}`)
  await page.locator('#main-checkin-account-0-api-user').fill(`api-${suffix}`)
  await page.locator('#main-checkin-account-0-cookies').fill('{"session":"cookie"}')
  await selectAppOption(page, '#main-checkin-account-0-linux-mode', /单账号|Single/)
  await page.locator('#main-checkin-account-0-linux-user').fill(`linux-${suffix}`)
  await page.locator('#main-checkin-account-0-linux-pass').fill('linux-password')
  await revealPasswordField(page, '#main-checkin-account-0-linux-pass')
  await page.locator('#main-checkin-account-0-linux-pass').fill('linux-password')
  await page.getByRole('button', { name: /保存配置|Save Config/ }).first().click()
  await expect(page.getByText(/配置已保存|Config saved/)).toBeVisible()

  await page.getByRole('button', { name: /新增账号|Add Account/ }).click()
  const secondAccount = page.getByText(/账号 2|Account 2/).first()
  await expect(secondAccount).toBeVisible()
  await page.getByRole('button', { name: /^移除$|^Remove$/ }).last().click()
  await page.getByRole('button', { name: /确认移除|Confirm Remove/ }).last().click()
  await expect(secondAccount).toHaveCount(0)

  await page.getByRole('button', { name: /立即运行|Run Now/ }).first().click()
  await expect(page.getByText(/已创建运行|Created run/)).toBeVisible()
  await expect(page.locator('.job-item').first()).toBeVisible()
  await page.locator('.job-item').first().click()
  await expect(page.locator('.console-card__toolbar')).toContainText(/[0-9a-f]{8}/)

  await page.goto('/aux-jobs')
  await waitForUiReady(page)
  const hub996 = page.locator('details').filter({ hasText: '996 hub' }).first()
  await hub996.locator('summary').click()
  await hub996.getByRole('button', { name: /^新增$|^Add$/ }).click()
  await hub996.getByRole('button', { name: /^移除$|^Remove$/ }).last().click()
  await hub996.getByRole('button', { name: /确认移除|Confirm Remove/ }).last().click()
  await hub996.getByLabel(/访问令牌|Access Token/).first().fill(`token-${suffix}`)
  await page.locator('#hub996-proxy').fill('{bad-json')
  await hub996.getByRole('button', { name: /保存配置|Save Config/ }).click()
  await expect(page.getByText(/JSON 格式不正确|Invalid JSON/)).toBeVisible()
  await page.locator('#hub996-proxy').fill('{"server":"http://127.0.0.1:8888"}')
  await hub996.getByRole('button', { name: /保存配置|Save Config/ }).click()
  await expect(hub996.getByText(/配置已保存|Config saved/)).toBeVisible()

  const qaq = page.locator('details').filter({ hasText: 'qaq.al' }).first()
  await qaq.locator('summary').click()
  await qaq.getByLabel(/SID/).first().fill(`sid-${suffix}`)
  await page.locator('#qaq-tier').fill('3')
  await qaq.getByRole('button', { name: /保存配置|Save Config/ }).click()
  await expect(qaq.getByText(/配置已保存|Config saved/)).toBeVisible()

  const linuxdo = page.locator('details').filter({ hasText: /Linux\.do 阅读|Linux\.do Read/ }).first()
  await linuxdo.locator('summary').click()
  await linuxdo.getByRole('button', { name: /^新增$|^Add$/ }).click()
  await linuxdo.getByRole('button', { name: /^移除$|^Remove$/ }).last().click()
  await linuxdo.getByRole('button', { name: /确认移除|Confirm Remove/ }).last().click()
  await linuxdo.getByLabel(/用户名|Username/).first().fill(`linuxdo-${suffix}`)
  await linuxdo.getByLabel(/密码|Password/).first().fill('linuxdo-password')
  await page.locator('#linuxdo-base-topic-id').fill('100001')
  await page.locator('#linuxdo-max-posts').fill('10')
  await linuxdo.getByRole('button', { name: /保存配置|Save Config/ }).click()
  await expect(linuxdo.getByText(/配置已保存|Config saved/)).toBeVisible()

  await linuxdo.getByRole('button', { name: /立即运行|Run Now/ }).click()
  await expect(page.getByText(/已创建运行|Created run/)).toBeVisible()
  await expect(page.locator('.job-item').first()).toBeVisible()
})
